### ISSUE TITLE
Errors while running SAFE-Dojo-master and SAFE-Dojo-suggested-solution

### ISSUE THREAD

**Issue by MiroslavHustak** [CompositionalIT/SAFE-Dojo#145]
Using dotnet run in the SAFE-Dojo-master folder as well as in the SAFE-Dojo-suggested-solution folder ended with errors. Please see the attached file with a complete list of error messages. 

[errormsg.txt](https://github.com/CompositionalIT/SAFE-Dojo/files/9944132/errormsg.txt)

**Comment by allenu** [comment]
I was just trying out this project and encountered this as well. I'm running on a Mac, if it makes a difference.

**Comment by IMPF-sfarley** [comment]
A temporary fix is to set the node_options environment variable.

For example, in powershell
```
$env:NODE_OPTIONS="--openssl-legacy-provider"
```

The better fix would be to update npm package versions, since the older node SSL provider [has security issues](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported).

**Comment by MiroslavHustak** [comment]
The fix had no effect. 
Currently using {"npm":"8.19.2","node":"v18.12.0"}.

**Comment by johanvts** [comment]
If you are still struggling, I finally have a version that works (on my machine) here: https://github.com/CompositionalIT/SAFE-Dojo/pull/157 Good luck.
