### ISSUE TITLE
Error calling IDojoApi

### ISSUE THREAD

**Issue by pth65** [CompositionalIT/SAFE-Dojo#185]
Hi,
I would like to learn SAFE stack using this nice project but I can't run it properly.
When I start it, I can see the main page and select a postcode but the search fails with the following error:
(On Windows 11, net8.0)
I tried another SAFE project I found on GitHub but it also failed when calling the server API (another API of course but same error).
Thank you for any help.

![image](https://github.com/user-attachments/assets/2c2183e1-ddd2-41c9-b64f-6cc3c6942471)

**Comment by jwthomson** [comment]
It looks like there may be some kind of error in the server startup. See the message "Unable to bind to http://localhost:5000 ..."

Then when Vite tries to proxy it fails because it is not getting the response it expects from the server.

A quick search for the error message turned up this StackOverflow question: https://stackoverflow.com/questions/10461257/ which has some ideas, including possibly restarting your Host Network Service, or that the port is already in use.

Can you try the suggestions from StackOverflow please, and see if any of them fix it?

**Comment by pth65** [comment]
Thank you very much, it fixed my problem (I mean using another port or closing the service using this port).
 I didn't see this "Unable to bind to ..." error as it was displayed in blue.
May be it would be better to display it in red or at least in a different color (warning color) ?

**Comment by jwthomson** [comment]
I've added an issue to the SAFE template repo, so hopefully this will be a better experience in the future 😄 

https://github.com/SAFE-Stack/SAFE-template/issues/633
