### ISSUE TITLE
PassGenerics Attribute for proposed getJsonSafe<'T> function

### ISSUE THREAD

**Issue by WalternativE** [CompositionalIT/SAFE-Dojo#34]
In the current version of the Dojo tutorial the `getJsonSafe<'T>` function is defined without the `PassGenerics` attribute. At least in the version of Fable I used to go trough the Dojo this caused deserialization failures at runtime. Is this just an oddity in my setup or can someone reproduce this?

The error occurred when rewriting the distance endpoint to use POST instead of GET to pass the zip code.

**Comment by isaacabraham** [comment]
Hmmm. A couple of people have pointed out some strange behaviour with POST instead of GET, although I can't remember whether that was the same issue. One of us will have a look in the next day or two at this!

**Comment by isaacabraham** [comment]
@bruinbrown can you take a look at this tomorrow?

**Comment by bruinbrown** [comment]
I've managed to replicate this and it looks like it's just caused by if you follow the instructions and create the helper function. If you call the .text and ofJson directly then you don't see the error. I've got an update to the instructions which talks about how you need to add the PassGenerics attribute if you create it as a function
